version: 0.0
os: linux

files:
  - source: build/libs/
    destination: /home/ubuntu/app/
  - source: deploy-scripts/
    destination: /home/ubuntu/deploy-scripts/

permissions:
  - object: /home/ubuntu/deploy-scripts/
    mode: "755"

hooks:
  ApplicationStop:
    - location: deploy-scripts/stop.sh
      timeout: 60
      runas: ubuntu
  ApplicationStart:
    - location: deploy-scripts/start.sh
      timeout: 120
      runas: ubuntu
  ValidateService:
    - location: deploy-scripts/health_check.sh
      timeout: 60
      runas: ubuntu